#!/bin/bash
# GENERATED by tools/section_plan.sh; PLAN: sections=0,0g,0h bearing=4 chunks=4
EIGS_PLAN_ACTIVE=1; export EIGS_PLAN_ACTIVE
EIGS_PLAN_TESTS_DIR='/home/jon/src/wt/queue-1444-operator-line-20261002/tests'; export EIGS_PLAN_TESTS_DIR
EIGS_SECTION_TIME=1; export EIGS_SECTION_TIME
# EIGS-EXPECT	530	1	[0] Opcode ABI Guard
# EIGS-EXPECT	651	1	[0g] After a call returns, a raise reports the caller's line (#1424)
# EIGS-EXPECT	741	1	[0h] Non-enforcing allocation-accounting instrument (#1319)
# EIGS-EXPECT	7642	1	[0h] Multiline binary errors report the operator's line (#1425)
#!/bin/bash
# Note: no `set -e`. This is a test runner — it must continue past a failing
# command and report its own PASS/FAIL tally. With `set -e`, any .eigs program
# that legitimately exits non-zero (an uncaught runtime error, or a probe that
# intentionally hits a missing builtin in the minimal build) would abort the
# whole suite.
# #1160: a generated section-plan runner lives outside tests/, so it has to be
# told where tests/ is. Unset — every ordinary invocation — this resolves from
# $0 exactly as before.
TESTS_DIR="${EIGS_PLAN_TESTS_DIR:-$(cd "$(dirname "$0")" && pwd)}"
export WERROR_FLAGS_FILE="$TESTS_DIR/../tools/werror_flags.txt"
. "$TESTS_DIR/../tools/read_werror_flags.sh" || exit 1
export EIGS_TEST_DIR="$TESTS_DIR"
. "$TESTS_DIR/failure_output.sh" || exit 1
. "$TESTS_DIR/suite_program_env.sh" || exit 1
cd "$TESTS_DIR/../src" || { echo "cannot cd to src"; exit 1; }

# Shard and changed-sections modes (EIGS_SUITE_SHARD / EIGS_SUITE_CHANGED).
. "$TESTS_DIR/suite_plan.sh" || exit 1

PASS=0
FAIL=0
TOTAL=0
LEAKED=0
# A section that SKIPPED measured nothing, and round 5's ILP32 gate (deleted, #1274) proved that
# "measured nothing" is invisible here: the section subtracted itself from
# TOTAL and the RESULTS line said nothing at all, so a lane that examined 23
# translation units last week and 0 this week read exactly like a clean run
# (measured by a blind critic, 2026-09-21). Every lane now prints `skipped=N`,
# `skipped=0` included — a zero that is printed is a claim; a number that is
# absent is not reviewable.
SKIPPED=0

# ONE helper prints a section-level skip and counts it. Round 6 incremented
# SKIPPED at exactly ONE site (the since-deleted ILP32 gate) while this file has ~40 lines
# that put a SKIP marker on a run's stdout — so the pushed head's own
# `linux / gcc` log printed `RESULTS: 5282/5282 passed, 0 failed, 0 skipped`
# beneath nine of them, including the former [99i] cache skip
# (measured by a blind critic, 2026-09-21).
# A printed zero is a claim, and that one was false on every lane.
#
# WHAT GOES THROUGH HERE: a SECTION-LEVEL skip — one where the section's
# verdict IS the skip, i.e. it contributed no PASS and no FAIL on this lane.
# Several of those used to add PASSes instead (the bench asset, the --pkg
# rows, [99c], [99d], [137]); a skip counted as a pass is the same disease one
# layer down, so they are counted here and NOT in PASS.
#
# WHAT DOES NOT: a SUB-CHECK skip, one line inside a section that still PASSes
# on its other checks. Ten of those remain, by design, and they are pinned by
# NAME in tools/section_plan.sh --skip-audit (suite section [99w]), which fails
# when a new bare `SKIP:` line appears in this file without a reviewed reason.
# A relay hands this helper the child's own line; the prefix is normalised so
# exactly one `  SKIP: ` is printed however the child spelled it.
section_skip() {
    local __sk_reason="$1"
    __sk_reason=${__sk_reason#"${__sk_reason%%[! 	]*}"}
    __sk_reason=${__sk_reason#SKIP:}
    __sk_reason=${__sk_reason#"${__sk_reason%%[! 	]*}"}
    echo "  SKIP: $__sk_reason"
    SKIPPED=$((SKIPPED + 1))
}

# ---- per-section wall time (#1160 round 4) --------------------------------
# Sharding the ASan suite across parallel CI jobs needs per-section COST, not
# per-section count, and a cost nobody measures is a guess. `echo` is shadowed
# here for the same reason `bash` already is below: one seam beats 263 call
# sites. Every line that OPENS a section — the `[nn] Title` convention that
# tools/suite_label_check.sh already polices — closes the timer on the previous
# section and prints
#     SECTION_TIME: [nn] <seconds>
# tools/section_weights.txt is regenerated from those lines (see docs/CI.md).
#
# Cost: one bash function call per echo. Measured over a full run: under 0.2 s.
# `EPOCHREALTIME` is bash 5; macOS ships bash 3.2, so $SECONDS is the fallback
# and the timer degrades to whole seconds there rather than failing.
# Set EIGS_SECTION_TIME=0 to silence the lines (the timing still costs nothing).
: "${EIGS_SECTION_TIME:=1}"
__eigs_now_us() {
    local t
    if [ -n "${EPOCHREALTIME:-}" ]; then
        t=${EPOCHREALTIME/,/.}
        builtin echo "${t%.*}${t#*.}"
    else
        builtin echo "$(( SECONDS * 1000000 ))"
    fi
}
__EIGS_SEC_LABEL=""
__EIGS_SEC_T0=""
__eigs_section_close() {
    [ -n "$__EIGS_SEC_LABEL" ] || return 0
    local now d
    now=$(__eigs_now_us)
    d=$(( now - __EIGS_SEC_T0 ))
    [ "$d" -ge 0 ] || d=0
    [ "$EIGS_SECTION_TIME" = "1" ] &&         builtin printf 'SECTION_TIME: %s %d.%02d\n' "$__EIGS_SEC_LABEL" "$(( d / 1000000 ))" "$(( (d % 1000000) / 10000 ))"
    __EIGS_SEC_LABEL=""
    return 0
}
echo() {
    case "${1:-}" in
        \[*\]*)
            __eigs_section_close
            __EIGS_SEC_LABEL="${1%%]*}]"
            __EIGS_SEC_T0=$(__eigs_now_us)
            ;;
    esac
    builtin echo "$@"
}


# Runaway guard for every .eigs invocation (test blocks via check_eigs_suite,
# and the [97] example programs). GNU `timeout` is the backstop; on a stock
# macOS (BSD userland) it isn't present, so fall back to gtimeout, or to no
# wrapper (degrade rather than fail). This is a RUNAWAY backstop, not a latency
# assertion: the budget is deliberately generous so it never fires on a
# slow-but-working test on the slow dev box (N3350, examples take up to ~60s
# under ASan — see #616), only on a genuine hang (an infinite loop in a test
# file, #648). Override with EIGS_TEST_TIMEOUT (seconds) to demonstrate the
# guard fast without burning the full budget.
: "${EIGS_TEST_TIMEOUT:=180}"

# Bytecode-verifier self-check: hold the C compiler's OWN output to the verifier
# that gates untrusted chunks (chunk_verify, including the stack-height pass that
# closed the sandbox_run underflow). The pass models the stack effect of ~90
# opcodes, and a row that drifts out of lockstep with vm.c fails silently in both
# directions — too strict refuses legitimate bytecode from an external producer
# (ouroboros' self-hosted codegen), too lax reopens the hole. Every .eigs the
# suite already runs becomes a sample of that table for one O(code_len) walk per
# compile; a mismatch exits 70 naming the chunk and the offset, which rc_ok
# fails. Set EIGS_VERIFY_SELF=0 to opt a run out.
: "${EIGS_VERIFY_SELF:=1}"
export EIGS_VERIFY_SELF

EIGS_TMO=""
if command -v timeout >/dev/null 2>&1; then EIGS_TMO="timeout $EIGS_TEST_TIMEOUT"
elif command -v gtimeout >/dev/null 2>&1; then EIGS_TMO="gtimeout $EIGS_TEST_TIMEOUT"; fi

# Binary fingerprint guard (#681). src/eigenscript is a hard link to the
# last `make` variant target (#740); re-pointing it mid-suite — or relinking
# the same variant — swaps the binary under us and invalidates the tally.
# Record a fingerprint at suite start and re-check at section seams. (stat
# -L and the symlink-aware [99d] restore below cost nothing on a hard link
# and keep the guard correct if the alias is ever a symlink.)
EIGS_BIN="./eigenscript"
# RUNTIME IDENTITY FOR EVERY CHILD (#1188). Eight child tests resolve their
# runtime as `${EIGS:-<some default>}`, so an EIGS inherited from the
# environment chooses the binary they measure. A blind critic exported one at
# a healthy build, ran the suite's own string-scaling section against the
# PRE-FIX quadratic tree, and got a clean PASS. Binding it at each dispatch
# site would work exactly until the next site forgot, so it is bound ONCE
# here, centrally, the way #988's child accounting is central: the cwd is
# already this suite's src directory (the cd at the top of this file), so
# $EIGS_BIN resolves against it, and the absolute form survives the children
# that cd into fixture directories. Children that hard-set their own EIGS are
# unaffected; nothing in the runtime reads a bare `EIGS`.
EIGS="$PWD/${EIGS_BIN#./}"
export EIGS

eigs_binary_fingerprint() {
    # -L: dereference — cksum reads through a symlink, so the size/mtime
    # half must describe the same file the cksum half does (#740 made
    # src/eigenscript a symlink to build/<variant>/eigenscript).
    local cksum size mtime
    cksum=$(cksum "$EIGS_BIN")
    if stat -L -c '%s %Y' "$EIGS_BIN" >/dev/null 2>&1; then
        read -r size mtime <<<"$(stat -L -c '%s %Y' "$EIGS_BIN")"
    else
        read -r size mtime <<<"$(stat -L -f '%z %m' "$EIGS_BIN")"
    fi
    printf '%s %s %s\n' "$cksum" "$size" "$mtime"
}

# #1089: the alias must be CURRENT before the fingerprint is recorded. A
# `make` that fails partway leaves the previous binary linked, and a suite
# launched afterwards measures that binary against the current sources and
# tests (bought 2026-09-03: 25 failures from a debug print whose source had
# already been reverted; `grep` on the tree answered 0). The #681 guard
# cannot see it -- it detects a binary that CHANGES during the run, not one
# stale at the start. Same answer as tests/aux_binary.sh for eigenlsp/eigsdap:
# ask the build system (`make -q <target>`, the real post-expansion
# dependency graph), never an mtime glob. The variant is whichever
# build/<variant>/eigenscript the alias is hard-linked to, and that FILE is
# the make target queried (the phony goals always answer "remake"). No matching variant (a binary carried
# in from elsewhere) or a `make -q` error is reported and NOT gated on --
# the suite cannot decide, so it says so instead of pretending.
ensure_binary_current() {
    local ino variant target rc
    ino=$(stat -c %i "$EIGS_BIN" 2>/dev/null) || return 0
    variant=""
    for cand in ../build/*/eigenscript; do
        [ -f "$cand" ] || continue
        if [ "$(stat -c %i "$cand" 2>/dev/null)" = "$ino" ]; then
            variant=$(basename "$(dirname "$cand")"); break
        fi
    done
    if [ -z "$variant" ]; then
        echo "  NOTE: src/eigenscript is not hard-linked to any build/<variant>/eigenscript -- freshness not checked (#1089)"
        return 0
    fi
    # The FILE target, not the phony goal: `make -q build` is always
    # "needs remaking" because `build` is .PHONY.
    target="build/$variant/eigenscript"
    make -q --no-print-directory -C .. "$target" >/dev/null 2>&1; rc=$?
    if [ "$rc" -eq 0 ]; then return 0; fi
    if [ "$rc" -ne 1 ]; then
        echo "  NOTE: make -q $target answered rc=$rc -- freshness not checked (#1089)"
        return 0
    fi
    # Rebuild through the variant's GOAL, not the file: only the goal
    # re-points the src/eigenscript hard link (RELINK); rebuilding the file
    # alone left the alias on the old inode (found by the plant).
    local goal="$variant"; [ "$variant" = "release" ] && goal="build"
    echo "  NOTE: src/eigenscript ($variant) is older than its sources -- rebuilding (make $goal) (#1089)"
    if ! make --no-print-directory -C .. "$goal" >/dev/null 2>&1; then
        echo "ERROR: rebuild of src/eigenscript ($goal) FAILED -- the linked binary is stale and the suite will not run it (#1089)"
        exit 1
    fi
    if [ "$(stat -c %i "$EIGS_BIN")" = "$ino" ] && ! make -q --no-print-directory -C .. "$target" >/dev/null 2>&1; then
        echo "ERROR: src/eigenscript is still stale after the rebuild (#1089)"
        exit 1
    fi
}

record_binary_fingerprint() {
    if [ ! -f "$EIGS_BIN" ]; then
        echo "ERROR: $EIGS_BIN not found — cannot run suite"
        exit 1
    fi
    ensure_binary_current
    EIGS_BIN_FINGERPRINT=$(eigs_binary_fingerprint)
}

check_binary_fingerprint() {
    local current
    if [ ! -f "$EIGS_BIN" ]; then
        echo "ERROR: src/eigenscript changed during the run (rebuilt mid-suite) — results are invalid."
        exit 1
    fi
    current=$(eigs_binary_fingerprint)
    if [ "$current" != "$EIGS_BIN_FINGERPRINT" ]; then
        echo "ERROR: src/eigenscript changed during the run (rebuilt mid-suite) — results are invalid."
        exit 1
    fi
}

# Exit-code gate for .eigs test programs. rc=0 passes. A nonzero rc whose
# output carries a LeakSanitizer report AND NOTHING HARDER is tolerated with a
# warning tally. The env<->fn closure cycles are reclaimed by the cycle
# collector now (docs/CLOSURE_CYCLE_GC.md — section [87] gates those shapes
# strictly); the residual tolerated reports are spawn()-thread programs (the
# collector is disabled once multithreaded) and a handful of pre-existing
# non-closure leak shapes. Everything else nonzero — crashes, asserts,
# UBSan — fails.
#
# #969: this used to tolerate ANY output containing the LeakSanitizer marker,
# so a heap-use-after-free or a UBSan diagnostic riding along in the same
# capture was counted as a tolerated leak and the run went green. The
# classification now lives in tests/lsan_classify.sh, is shared with
# test_sigusr1_dump.sh, and is mutation-proven by tests/test_lsan_classify.sh.
# A HARD diagnostic fails at ANY exit code, including 0. The repo's ASAN_FLAGS
# (Makefile) do not pass -fno-sanitize-recover, so GCC's UBSan checks are
# recoverable: a program hits signed-integer-overflow, prints
#   file.c:3:36: runtime error: signed integer overflow: 2147483647 + 1 ...
# then CONTINUES and exits 0. ASan under halt_on_error=0 behaves the same way
# for a double-free. An `[ "$1" = "0" ] && return 0` fast path never looks at
# the output in either case, so the diagnostic is tolerated exactly the way
# #969 was — the fix for #969 does not cover it, because the masking happens
# before the classifier is consulted rather than inside it.
. "$TESTS_DIR/lsan_classify.sh"

rc_ok() {
    local _cls
    # rc_ok is export -f'd into child shells (sections [99c]/[99d]). `export -f`
    # carries only the functions it NAMES, so a child that got rc_ok without
    # lsan_classify would run `lsan_classify: command not found`, take $? = 127,
    # and invert BOTH bars at once: 127 is not 1 so a hard diagnostic at rc=0
    # would be tolerated, and 127 is not 0 so genuine leak-only output would be
    # failed. That is silent in a child shell. Refuse loudly instead — a missing
    # classifier is a broken harness, never a verdict.
    if ! declare -F lsan_classify >/dev/null 2>&1; then
        echo "  FAIL: rc_ok called without lsan_classify in scope — harness bug;" \
             "add it to the export -f list at this call site" >&2
        return 1
    fi
    lsan_classify "$2"
    _cls=$?
    # hard: never tolerated, whatever the exit code says.
    [ "$_cls" -eq 1 ] && return 1
    [ "$1" = "0" ] && return 0
    if [ "$_cls" -eq 0 ]; then
        LEAKED=$((LEAKED + 1))
        return 0
    fi
    return 1
}

# ---- #988: child `.sh` tests gate on exit status, not just markers ----------
# rc_ok (above) fixed exactly this disease for `.eigs` programs: "marker-grep
# alone used to let a crash *after* correct output pass". The ~45 child `.sh`
# tests were still on the marker-only side of that line, because the
# idiomatic call site is
#     FOO_OUTPUT=$(bash "$TESTS_DIR/test_foo.sh" 2>&1)
# and a command substitution keeps the child's stdout while DISCARDING its
# exit status. The section then decided purely on `grep -c "FAIL:"`. So a
# child that printed two PASS: lines and then segfaulted reported a passing
# section, and a child that did not exist at all (127) reported
# "0/0 passed, 0 failed" — also a pass. Reproduced at 139, 127 and 1.
#
# The fix is central rather than 45 local `$?` checks, because the local form
# is exactly what every future site would have to remember. `bash` is a
# function here, so every child invocation is routed through it; when a child
# exits nonzero it emits a synthetic `FAIL:` line on the child's own stdout.
# That lands inside the caller's `$(...)` capture, so the EXISTING per-site
# `grep -c "FAIL:"` logic counts it and the section fails, with no site edit.
# Sites that stream rather than capture still see it on the terminal, and
# their `if bash ...; then` already reads the status directly.
#
# The ledger is a FILE, not a variable: the increment happens inside the
# caller's command substitution, i.e. in a subshell, so a shell variable would
# be discarded along with everything else the subshell touched — the same
# class of loss this whole section is about.
#
# The second half of the bar — "a section that executes zero checks must not
# report itself as passing" — is NOT covered by exit status: a child can exit
# 0 having done nothing, and `[42] CLI & REPL` then prints
# "PASS: all 0 CLI checks" and contributes 0 to TOTAL, so even the RESULTS
# line looks untouched. For the `test_*.sh` population (46 of 48 follow the
# marker convention) the child's output is therefore captured and a run with
# NO markers at all is failed as vacuous. Capture is confined to that
# population deliberately: the `tools/*.sh` gates print their own prose, and
# buffering their output would change what a reader sees for no gain.
#
# Two side effects of capturing, stated because they are real and small:
# `$(...)` strips trailing newlines (one is added back, so a child ending in
# several blank lines loses them), and a captured child's stderr now reaches
# the caller BEFORE its stdout rather than interleaved. Neither changes marker
# counting, which is what every section decides on; both would matter to a
# section that parsed output by line position, and none does.
#
# tools/child_exit_check.sh is the drift gate. Note it must check that `bash`
# is the COMMAND WORD, not merely that no known-bad spelling appears: this is
# a shell FUNCTION, so `env bash …`, `timeout 60 bash …` or `$EIGS_TMO bash …`
# exec the real binary and silently leave the mechanism entirely — while still
# looking like ordinary call sites.
#
# There is NO expect-nonzero exemption, because nothing needs one: the only
# deliberately-aborting child in the suite is section [99f]'s fingerprint
# self-test, and it runs `bash -c '...'` (an inline program, not a script
# file), which this function does not account for. If a future site genuinely
# needs to exit nonzero on purpose, it gets an exemption WITH its reason then.
CHILD_LEDGER="${CHILD_LEDGER:-$(mktemp "${TMPDIR:-/tmp}/eigs_child_ledger.XXXXXX")}"
export CHILD_LEDGER
: > "$CHILD_LEDGER"
# The suite has several `exit 1` paths before [99p] (the mid-run-rebuild abort
# among them) and can be interrupted; without this the ledger leaks one file
# per aborted run. The runner has no other trap — `trap ... EXIT` REPLACES
# rather than accumulates, so if one is ever added it must call this too.
trap 'rm -f "${CHILD_LEDGER:-}"' EXIT
# Children that legitimately emit no PASS:/FAIL: markers, so the vacuity rule
# must not fire on them. Each is a waiver and states why; an entry that stops
# being needed is a review event, and tools/child_exit_check.sh pins the list
# against the tree so it cannot silently grow.
#   test_lsp.sh — thin wrapper that execs test_lsp.py, whose tally uses a
#   different format. test_lsp_asan.sh has its own instrumentation FAIL gate.
CHILD_NO_MARKERS=" test_lsp.sh "
bash() {
    # Resolve the script path first: it decides whether this invocation is
    # accounted for at all, and whether its output must be captured.
    local __a __what="" __skipnext=0
    for __a in "$@"; do
        if [ "$__skipnext" = "1" ]; then __skipnext=0; continue; fi
        case "$__a" in
            -c) __what=""; break ;;
            # Options that CONSUME the next word; without this the value is
            # mistaken for the script path and a real child escapes accounting
            # (`bash -o pipefail t.sh` bound __what=pipefail).
            -o|-O|--rcfile|--init-file) __skipnext=1 ;;
            --) __skipnext=0 ;;
            -*) ;;
            *) __what="$__a"; break ;;
        esac
    done
    case "$__what" in
        *.sh) ;;
        *) command bash "$@"; return $? ;;
    esac

    local __base="${__what##*/}"
    local __rc __out=""
    case "$__base" in
        test_*)
            # Capture so the vacuity rule can see the markers, then replay
            # verbatim so every existing call site is unaffected.
            __out=$(command bash "$@")
            __rc=$?
            [ -n "$__out" ] && printf '%s\n' "$__out"
            ;;
        *)
            command bash "$@"
            __rc=$?
            ;;
    esac

    if [ "$__rc" -ne 0 ]; then
        local __why="exited $__rc"
        [ ! -f "$__what" ] && __why="is missing (exit $__rc)"
        echo "  FAIL: $__base $__why without completing — section verdict is not trustworthy (#988)"
        printf '%s\t%s\n' "$__rc" "$__what" >> "$CHILD_LEDGER"
        return $__rc
    fi

    # Exit 0 — but did it actually check anything? A section reporting
    # "all 0 checks" as a pass is the other half of #988.
    case "$__base" in
        test_*)
            case "$CHILD_NO_MARKERS" in
                *" $__base "*) return 0 ;;
            esac
            # SKIP: counts as reporting. The disease #988 is about is
            # SILENCE — a child that ran nothing and said nothing, whose
            # section then printed "all checks" as a pass. A child that
            # prints `SKIP:` has honestly declined to measure, which is
            # visible to the reader and is the suite's established
            # convention for an unavailable tool. Bought in CI (PR #996):
            # test_temporal_memory.sh skips without GNU `time -f`, without
            # /proc, and on sanitizer builds — all three exist on the dev
            # box, so the local run never took those paths and four lanes
            # went red on a child doing exactly what it was designed to do.
            if ! printf '%s\n' "$__out" | grep -q -E '(PASS|FAIL|SKIP):'; then
                echo "  FAIL: $__base exited 0 but reported no checks at all — a section cannot pass on zero checks (#988)"
                printf '%s\t%s\n' "vacuous" "$__what" >> "$CHILD_LEDGER"
                return 1
            fi
            ;;
    esac
    return 0
}

check() {
    TOTAL=$((TOTAL + 1))
    local test_name="$1"
    local actual="$2"
    local expected="$3"
    if [ "$actual" = "$expected" ]; then
        echo "  PASS: $test_name"
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $test_name (got '$actual', expected '$expected')"
        FAIL=$((FAIL + 1))
    fi
}

check_numeric() {
    TOTAL=$((TOTAL + 1))
    local test_name="$1"
    local actual="$2"
    local min="$3"
    local max="$4"
    if [ -z "$actual" ]; then
        echo "  FAIL: $test_name (empty value)"
        FAIL=$((FAIL + 1))
        return
    fi
    local in_range
    in_range=$(python3 -c "import sys; v=float(sys.argv[1]); lo=float(sys.argv[2]); hi=float(sys.argv[3]); print(1 if lo <= v <= hi else 0)" "$actual" "$min" "$max" 2>/dev/null || echo "0")
    if [ "$in_range" = "1" ]; then
        echo "  PASS: $test_name ($actual in [$min, $max])"
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $test_name ($actual not in [$min, $max])"
        FAIL=$((FAIL + 1))
    fi
}

# Derive a suite block's internal check count from its own output.  A child that
# does not report a count is one suite-level result; no literal fallback is kept
# in this runner (#1430).
derive_count() {
    local out="$1" label="${2:-}" n
    n=$(printf '%s\n' "$out" | sed -n 's/.*Tests: \([0-9][0-9]*\).*/\1/p' | tail -1)
    if [ -n "$n" ]; then
        printf '%s' "$n"
    else
        printf '1'
        [ -n "$label" ] && echo "  NOTE(#654): $label produced no 'Tests: N' count line; tally uses one suite result" >&2
    fi
}

# Run a self-checking .eigs suite file.  Each invocation contributes one
# suite-level result; assertion totals remain owned by the child (#1430).
check_eigs_suite() {
    local test_name="$1"
    local file="$2"
    local marker="$3"
    local out rc n=1
    # Guard #681: abort if the binary was rebuilt while a previous block ran.
    check_binary_fingerprint
    out=$($EIGS_TMO ./eigenscript "../tests/$file" </dev/null 2>&1); rc=$?
    TOTAL=$((TOTAL + n))
    if [ "$rc" = "124" ]; then
        # rc=124 is the runaway guard (GNU/gtimeout both use it): the test file
        # never terminated. Name the block so the failure points at the culprit
        # instead of folding into the generic rc path — and let the suite continue.
        FAIL=$((FAIL + n))
        echo "  FAIL: $test_name (timed out after ${EIGS_TEST_TIMEOUT}s — runaway in $file)"
    elif rc_ok "$rc" "$out" && echo "$out" | grep -q "$marker"; then
        PASS=$((PASS + n))
        echo "  PASS: $test_name"
    else
        FAIL=$((FAIL + n))
        echo "  FAIL: $test_name (rc=$rc)"
        printf '%s\n' "$out" | eigs_failure_output
    fi
}

# A JIT/OSR row that compiled nothing measured the interpreter ([0b], [0g]).
lar_jit_witness() {   # lar_jit_witness <tier> <output>: prints ok | none
    if [ "$1" = "EIGS_JIT_OFF=1" ] || [ "$(uname -m)" != x86_64 ] ||
       grep -qE '^\[jit\] scanned=[0-9]+ compiled=[1-9]' <<< "$2"; then echo ok; else echo none; fi
}

echo "============================================"
echo "  EigenScript Gen 0 Compliance Test Suite"
echo "============================================"
echo ""

# Record the binary fingerprint at suite start; every section seam re-checks it.
record_binary_fingerprint

__eigs_chunk_status=$?
builtin echo '@@EIGS-CHUNK 530@@'
(exit "$__eigs_chunk_status")
echo "[0] Opcode ABI Guard"
check_binary_fingerprint
TOTAL=$((TOTAL + 1))
OP_ABI_OUT=$(${CC:-gcc} -std=c11 $WERROR_FLAGS -I. \
    -DEIGENSCRIPT_EXT_HTTP=0 \
    -DEIGENSCRIPT_EXT_MODEL=0 \
    -DEIGENSCRIPT_EXT_DB=0 \
    -c ../tests/test_opcode_abi.c -o /tmp/eigs_opcode_abi.o 2>&1)
OP_ABI_RC=$?
if [ "$OP_ABI_RC" = "0" ]; then
    PASS=$((PASS + 1))
    echo "  PASS: opcode numeric ABI unchanged"
else
    FAIL=$((FAIL + 1))
    echo "  FAIL: opcode numeric ABI changed"
    echo "$OP_ABI_OUT" | head -8
fi

# #964: descriptor strings are untrusted input and must be reclaimed at the
# sandbox-run boundary. This focused C test is part of the normal runner (and
# has its own Makefile target) so the retention assertion cannot disappear
# into a fork-only/manual probe.
__eigs_chunk_status=$?
builtin echo '@@EIGS-CHUNK 651@@'
(exit "$__eigs_chunk_status")
echo "[0g] After a call returns, a raise reports the caller's line (#1424)"
check_binary_fingerprint
# Pre-fix every e.line row in test_line_after_return.eigs and both uncaught
# headers named a line inside the callee (CASE(RETURN) and the JIT return
# helpers left the callee's current_line in place). Each tier is its own row:
# default JIT, interpreter, forced OSR. All three programs are hot (6001 calls
# or iterations, past the JIT entry and OSR thresholds; the fixtures return
# through RETURN and, in line_after_return_null, RETURN_NULL, since only the
# last return before a raise decides its line), and on x86_64 EVERY
# JIT/OSR row must show compiled thunks (lar_jit_witness, the one predicate):
# a row that compiled nothing measured the interpreter and FAILS by name.
# #1434: line_after_callback_halt's callback prints its own swallowed error
# first (#1426), with the same frame lines, so a fixture's frame lines are
# matched only from its header line onward.
for LAR_TIER in "JIT" "EIGS_JIT_OFF=1" "EIGS_JIT_OSR_THRESHOLD=1"; do
    LAR_ENV="EIGS_JIT_STATS=1"; [ "$LAR_TIER" = JIT ] || LAR_ENV="$LAR_ENV $LAR_TIER"
    LAR_OUT=$($EIGS_TMO env $LAR_ENV ./eigenscript ../tests/test_line_after_return.eigs </dev/null 2>&1); LAR_RC=$?
    TOTAL=$((TOTAL + 1))
    LAR_JIT=$(lar_jit_witness "$LAR_TIER" "$LAR_OUT")
    if [ "$LAR_JIT" != ok ]; then
        FAIL=$((FAIL + 1)); echo "  FAIL: e.line after a return ($LAR_TIER): compiled nothing, so it measured the interpreter"
    elif rc_ok "$LAR_RC" "$LAR_OUT" && grep -q "All tests passed" <<< "$LAR_OUT"; then
        PASS=$((PASS + 1)); echo "  PASS: e.line after a return ($LAR_TIER)"
    else
        FAIL=$((FAIL + 1)); echo "  FAIL: e.line after a return ($LAR_TIER, rc=$LAR_RC)"
        printf '%s\n' "$LAR_OUT" | eigs_failure_output
    fi
    for LAR_FX in "line_after_return_module.eigs:Error line 10:|  at <module> (line 10)" \
                  "line_after_return_fn.eigs:Error line 11:|  at outer (line 11)|  at <module> (line 15)" \
                  "line_after_return_null.eigs:Error line 13:|  at hot_null (line 13)|  at <module> (line 20)" \
                  "line_after_callback_halt.eigs:Error line 9:|  at hot_sb (line 9)|  at <module> (line 15)"; do
        LAR_FILE=${LAR_FX%%:*}; LAR_WANT=${LAR_FX#*:}
        LAR_OUT=$($EIGS_TMO env $LAR_ENV ./eigenscript "../tests/$LAR_FILE" </dev/null 2>&1); LAR_RC=$?
        LAR_MISS=""
        LAR_REST="$LAR_WANT|"
        LAR_TAIL=$(printf '%s\n' "$LAR_OUT" | sed 's/: .*/:/' | awk -v h="${LAR_WANT%%|*}" 'f || $0 == h { f = 1; print }')
        while [ -n "$LAR_REST" ]; do
            LAR_LINE=${LAR_REST%%|*}; LAR_REST=${LAR_REST#*|}
            grep -qxF -- "$LAR_LINE" <<< "$LAR_TAIL" || LAR_MISS="$LAR_MISS [$LAR_LINE]"
        done
        TOTAL=$((TOTAL + 1))
        LAR_JIT=$(lar_jit_witness "$LAR_TIER" "$LAR_OUT")
        if [ "$LAR_JIT" != ok ]; then
            FAIL=$((FAIL + 1)); echo "  FAIL: $LAR_FILE ($LAR_TIER): compiled nothing, so it measured the interpreter"
        elif [ "$LAR_RC" -eq 1 ] && [ -z "$LAR_MISS" ]; then
            PASS=$((PASS + 1)); echo "  PASS: uncaught header + traceback lines, $LAR_FILE ($LAR_TIER)"
        else
            FAIL=$((FAIL + 1)); echo "  FAIL: $LAR_FILE ($LAR_TIER, rc=$LAR_RC) missing:$LAR_MISS"
            printf '%s\n' "$LAR_OUT" | sed 's/^/      /'
        fi
    done
    # #1434: a callback builtin entered after a call RETURNED tapes the
    # statement's line, not the returned callee's (live: `what is x at 15`).
    LAR_TAPE=$(mktemp /tmp/eigs_lar_XXXXXX.tape); rm -f "$LAR_TAPE"
    LAR_OUT=$($EIGS_TMO env $LAR_ENV EIGS_TRACE="$LAR_TAPE" ./eigenscript ../tests/line_after_callback_tape.eigs </dev/null 2>&1); LAR_RC=$?
    LAR_STEP=$(printf 'c\njb 9\ns\nq\n' | $EIGS_TMO ./eigenscript --step "$LAR_TAPE" 2>&1 | sed -n 's/^step [0-9]*\/[0-9]* *line \([0-9]*\)$/\1/p' | tail -1)
    rm -f "$LAR_TAPE"
    TOTAL=$((TOTAL + 1))
    if [ "$(lar_jit_witness "$LAR_TIER" "$LAR_OUT")" != ok ]; then
        FAIL=$((FAIL + 1)); echo "  FAIL: line_after_callback_tape.eigs ($LAR_TIER): compiled nothing, so it measured the interpreter"
    elif [ "$LAR_RC" -eq 0 ] && grep -qx 2 <<< "$LAR_OUT" && [ "$LAR_STEP" = 15 ]; then
        PASS=$((PASS + 1)); echo "  PASS: tape stop after the callbacks is the statement's line 15 ($LAR_TIER)"
    else
        FAIL=$((FAIL + 1)); echo "  FAIL: line_after_callback_tape.eigs ($LAR_TIER, rc=$LAR_RC): tape stop '$LAR_STEP', want 15"
        printf '%s\n' "$LAR_OUT" | sed 's/^/      /'
    fi
done
echo ""

__eigs_chunk_status=$?
builtin echo '@@EIGS-CHUNK 741@@'
(exit "$__eigs_chunk_status")
echo "[0h] Non-enforcing allocation-accounting instrument (#1319)"
check_binary_fingerprint
ALLOC_STATS_OUT=$(EIGS_ALLOC_STATS=1 ./eigenscript -e 'print of len of range of 1000' 2>&1)
ALLOC_STATS_RC=$?
ALLOC_STATS_LINE=$(printf '%s\n' "$ALLOC_STATS_OUT" | sed -n 's/^eigs-alloc-stats: //p')
ALLOC_CUM=$(printf '%s\n' "$ALLOC_STATS_LINE" | sed -n 's/.*cumulative=\([0-9][0-9]*\).*/\1/p')
ALLOC_LIVE=$(printf '%s\n' "$ALLOC_STATS_LINE" | sed -n 's/.*live=\([0-9][0-9]*\).*/\1/p')
ALLOC_PEAK=$(printf '%s\n' "$ALLOC_STATS_LINE" | sed -n 's/.*peak=\([0-9][0-9]*\).*/\1/p')
ALLOC_OFF_OUT=$(EIGS_ALLOC_STATS=0 ./eigenscript -e 'print of 1' 2>&1)
TOTAL=$((TOTAL + 1))
if [ "$ALLOC_STATS_RC" -eq 0 ] && [ -n "$ALLOC_CUM" ] && [ -n "$ALLOC_LIVE" ] && [ -n "$ALLOC_PEAK" ] && \
   [ "$ALLOC_CUM" -ge "$ALLOC_PEAK" ] && [ "$ALLOC_PEAK" -ge "$ALLOC_LIVE" ] && \
   ! grep -q '^eigs-alloc-stats:' <<< "$ALLOC_OFF_OUT"; then
    PASS=$((PASS + 1)); echo "  PASS: opt-in counters report cumulative >= peak >= live; disabled path is silent"
else
    FAIL=$((FAIL + 1)); echo "  FAIL: allocation-accounting output (rc=$ALLOC_STATS_RC): $ALLOC_STATS_LINE"
fi
echo ""



# #1060: a native function registered with a name reports as a user fn.
# C-level for the same reason as [0b]: only a linked runtime makes one.
__eigs_chunk_status=$?
builtin echo '@@EIGS-CHUNK 7642@@'
(exit "$__eigs_chunk_status")
echo "[0h] Multiline binary errors report the operator's line (#1425)"
check_binary_fingerprint
# Keep #1424's caller-line section unchanged. These rows own #1425's
# diagnostics and restoration checks, with native execution witnesses.
for OL_TIER in "JIT" "EIGS_JIT_OFF=1" "EIGS_JIT_OSR_THRESHOLD=1"; do
    OL_ENV="EIGS_JIT_STATS=1 EIGS_JIT_HOT=1"; [ "$OL_TIER" = JIT ] || OL_ENV="$OL_ENV $OL_TIER"
    for OL_PROG in test_operator_line.eigs test_operator_line_parent.eigs; do
        OL_OUT=$($EIGS_TMO env $OL_ENV ./eigenscript "../tests/$OL_PROG" </dev/null 2>&1); OL_RC=$?
        TOTAL=$((TOTAL + 1))
        OL_JIT=$(lar_jit_witness "$OL_TIER" "$OL_OUT")
        if [ "$OL_PROG" = test_operator_line_parent.eigs ] && [ "$OL_TIER" != EIGS_JIT_OFF=1 ] && [ "$(uname -m)" = x86_64 ]; then
            # Witness each parent callee and each independent OSR loop.
            for OL_PARENT in unary index call; do
                grep -Eq "^parent_${OL_PARENT} +[0-9]+ +yes " <<< "$OL_OUT" || OL_JIT=missing-parent-$OL_PARENT
                grep -Eq "^osr_parent_${OL_PARENT} .* +yes +[1-9][0-9]* +[0-9]+ " <<< "$OL_OUT" || OL_JIT=missing-osr-$OL_PARENT
            done
            grep -Eq "^parent_branch +[0-9]+ +yes " <<< "$OL_OUT" || OL_JIT=missing-parent-branch
            grep -Eq "^osr_parent_branch .* +yes +[1-9][0-9]* +[0-9]+ " <<< "$OL_OUT" || OL_JIT=missing-osr-branch
        fi
        if [ "$OL_JIT" != ok ]; then
            FAIL=$((FAIL + 1)); echo "  FAIL: e.line, $OL_PROG ($OL_TIER): compiled witness $OL_JIT"
            printf '%s\n' "$OL_OUT" | eigs_failure_output
        elif rc_ok "$OL_RC" "$OL_OUT" && grep -q "All tests passed" <<< "$OL_OUT"; then
            PASS=$((PASS + 1)); echo "  PASS: e.line, $OL_PROG ($OL_TIER)"
        else
            FAIL=$((FAIL + 1)); echo "  FAIL: e.line, $OL_PROG ($OL_TIER, rc=$OL_RC)"
            printf '%s\n' "$OL_OUT" | eigs_failure_output
        fi
    done
    # Semicolons separate exact expected lines; excerpt lines contain '|'.
    for OL_FX in "operator_line_module.eigs:Error line 8:;     8 |     r is 1 / (;       |            ^;  at <module> (line 8)" \
                 "operator_line_fn.eigs:Error line 7:;     7 |         b +;       |           ^;  at chain (line 7);  at <module> (line 16)" \
                 "operator_line_compound.eigs:Error line 6:;     6 |     x += (;       |       ^;  at compound_add (line 6);  at <module> (line 14)"; do
        OL_FILE=${OL_FX%%:*}; OL_WANT=${OL_FX#*:}
        OL_OUT=$($EIGS_TMO env $OL_ENV ./eigenscript "../tests/$OL_FILE" </dev/null 2>&1); OL_RC=$?
        OL_SAN=$(lsan_classify_name "$OL_OUT")
        OL_MISS=""
        OL_REST="$OL_WANT;"
        OL_TAIL=$(printf '%s\n' "$OL_OUT" | sed 's/: .*/:/' | awk -v h="${OL_WANT%%;*}" 'f || $0 == h { f = 1; print }')
        while [ -n "$OL_REST" ]; do
            OL_LINE=${OL_REST%%;*}; OL_REST=${OL_REST#*;}
            grep -qxF -- "$OL_LINE" <<< "$OL_TAIL" || OL_MISS="$OL_MISS [$OL_LINE]"
        done
        TOTAL=$((TOTAL + 1))
        OL_JIT=$(lar_jit_witness "$OL_TIER" "$OL_OUT")
        if [ "$OL_FILE" = operator_line_compound.eigs ] && [ "$OL_TIER" != EIGS_JIT_OFF=1 ] && [ "$(uname -m)" = x86_64 ]; then
            grep -Eq "^compound_add +[0-9]+ +yes " <<< "$OL_OUT" || OL_JIT=missing-compound-add
        fi
        if [ "$OL_JIT" != ok ]; then
            FAIL=$((FAIL + 1)); echo "  FAIL: $OL_FILE ($OL_TIER): compiled witness $OL_JIT"
            printf '%s\n' "$OL_OUT" | eigs_failure_output
        elif [ "$OL_RC" -eq 1 ] && [ "$OL_SAN" = none ] && [ -z "$OL_MISS" ]; then
            PASS=$((PASS + 1)); echo "  PASS: header, excerpt, caret and traceback, $OL_FILE ($OL_TIER)"
        else
            FAIL=$((FAIL + 1)); echo "  FAIL: $OL_FILE ($OL_TIER, rc=$OL_RC, sanitizer=$OL_SAN) missing:$OL_MISS"
            printf '%s\n' "$OL_OUT" | eigs_failure_output
        fi
    done
done
echo ""
# Tensor-file cap contract (#1393); sourced by the suite fragment seam.
# Final guard (#681): if the binary changed during the last block, results are invalid.
check_binary_fingerprint

# Close the timer on the final section so the last row is not lost (#1160 r4).
__eigs_section_close

# #1430: each counted outcome owns a total slot. A mismatched denominator
# must fail even when every test passed; it used to print PASS > TOTAL.
if [ "$TOTAL" -ne "$((PASS + FAIL))" ]; then
    echo "  FAIL: suite result counters disagree (PASS=$PASS FAIL=$FAIL TOTAL=$TOTAL)"
    exit 1
fi

# A run that asserted NOTHING must not be green (#1160 round 2). The plan-level
# refusal catches "this variant selected zero sections"; this catches the other
# half — a plan whose every selected section SKIPPED at run time still printed
# "RESULTS: 0/0 passed, 0 failed" and exited 0, which reads exactly like a
# clean run. Unconditional, not plan-only: a FULL suite with zero assertions is
# never right either.
if [ "$TOTAL" -le 0 ]; then
    echo "============================================"
    echo "  FAIL: this run executed ZERO assertions (TOTAL=0)."
    echo "  A suite — or a section plan — that measured nothing is a harness"
    echo "  failure, not a pass (#1160)."
    echo "============================================"
    exit 1
fi

echo "============================================"
echo "  RESULTS: $PASS/$TOTAL passed, $FAIL failed, $SKIPPED skipped"
if [ "$LEAKED" -gt 0 ]; then
    echo "  NOTE: $LEAKED test program(s) exited nonzero on LeakSanitizer"
    echo "  reports (spawn-thread programs + known non-closure leak"
    echo "  shapes; counted as passes — closure cycles are collected)."
fi
echo "============================================"

if [ "$FAIL" -gt 0 ]; then
    exit 1
fi
