#!/bin/bash
# Emit the single-file embeddable amalgamation (#397): copy two files, call
# eigs_open. Produces:
#   build/eigenscript_all.c  — every runtime .c (minus main.c) with project
#                              headers inlined once, self-contained (system
#                              headers only, no -Isrc needed)
#   build/eigs_embed.h       — the self-contained public embedding header
#
# Anti-drift: the source list is read from the Makefile's SOURCES (the single
# source of truth), so a new .c can never be silently missed here.
set -eu
cd "$(dirname "$0")/.."
OUT="${1:-build}"
mkdir -p "$OUT"

# Read SOURCES from the Makefile, expand $(SRC_DIR)=src, drop the CLI-only
# units (main.c + repl.c — repl.c pulls termios, banned in the embed profile).
SOURCES=$(grep '^SOURCES :=' Makefile | sed 's/^SOURCES :=//; s/\$(SRC_DIR)/src/g' \
    | tr ' ' '\n' | grep '\.c$' | grep -v '/main\.c$' | grep -v '/repl\.c$')

python3 - "$OUT/eigenscript_all.c" $SOURCES <<'PY'
import re, sys, os
out_path = sys.argv[1]
sources  = sys.argv[2:]
inc_re   = re.compile(r'^\s*#\s*include\s*"([^"]+)"')
# Feature-test macros are hoisted once to the top; strip per-file copies so
# they don't redefine after system headers are already pulled in.
ftm_re   = re.compile(r'^\s*#\s*define\s+(_GNU_SOURCE|_POSIX_C_SOURCE|_DEFAULT_SOURCE|_XOPEN_SOURCE)\b')
seen = set()
buf  = []

def emit(path):
    path = os.path.normpath(path)
    for line in open(path, encoding='utf-8'):
        m = inc_re.match(line)
        if m:
            hdr = os.path.normpath(os.path.join('src', os.path.basename(m.group(1))))
            if os.path.exists(hdr):
                if hdr not in seen:
                    seen.add(hdr)
                    buf.append(f'/* ==== inlined header: {hdr} ==== */\n')
                    emit(hdr)
                # else: already inlined (include-guard semantics for one TU)
                # Preserve any trailing text after the directive — an include
                # line can open a multi-line comment (`#include "vm.h" /* ...`)
                # whose closing `*/` is on a later line; dropping it orphans it.
                tail = line[m.end():]
                if tail.strip():
                    buf.append(tail if tail.endswith('\n') else tail + '\n')
                continue
            # not a project header we bundle → keep as a system include
            buf.append(line); continue
        if ftm_re.match(line):
            continue
        buf.append(line)

buf.append('/* Generated by tools/amalgamate.sh — do not edit. */\n')
buf.append('#define _GNU_SOURCE 1\n')
# Default every optional extension OFF so the amalgamation is the minimal,
# zero-dependency build (no libpq/curl/SDL) unless the embedder opts in.
for flag in ('EIGENSCRIPT_EXT_HTTP', 'EIGENSCRIPT_EXT_MODEL',
             'EIGENSCRIPT_EXT_DB', 'EIGENSCRIPT_EXT_GFX'):
    buf.append(f'#ifndef {flag}\n#define {flag} 0\n#endif\n')
for c in sources:
    buf.append(f'\n/* ==================== {c} ==================== */\n')
    emit(c)

with open(out_path, 'w', encoding='utf-8') as f:
    f.write(''.join(buf))
print(f'  wrote {out_path} ({len(buf)} chunks, {len(seen)} headers inlined)')
PY

cp src/eigs_embed.h "$OUT/eigs_embed.h"
echo "  wrote $OUT/eigs_embed.h"
echo "Amalgamation ready in $OUT/ — compile: cc host.c $OUT/eigenscript_all.c -lm -lpthread"
