#!/usr/bin/env python3
"""Derive the captured-nondeterminism builtin set from trace hook calls."""

import argparse
import pathlib
import re
import sys

HOOK = re.compile(r"\bTRACE_NONDET_(?:RET|TAKE|RECORD)\s*\(")
STRING = re.compile(r'"((?:[^"\\]|\\.)*)"')


def mask_comments(text: str) -> str:
    """Blank comments while preserving strings and newlines."""
    out = list(text)
    i, state = 0, "code"
    while i < len(text):
        if state == "code" and text.startswith("//", i):
            out[i:i + 2] = "  "; i += 2; state = "line"; continue
        if state == "code" and text.startswith("/*", i):
            out[i:i + 2] = "  "; i += 2; state = "block"; continue
        if state == "line":
            if text[i] == "\n": state = "code"
            else: out[i] = " "
            i += 1; continue
        if state == "block":
            if text.startswith("*/", i): out[i:i + 2] = "  "; i += 2; state = "code"
            else:
                if text[i] != "\n": out[i] = " "
                i += 1
            continue
        if text[i] == '"':
            i += 1
            while i < len(text):
                if text[i] == "\\": i += 2; continue
                if text[i] == '"': i += 1; break
                i += 1
            continue
        i += 1
    if state == "block": raise ValueError("unterminated block comment")
    return "".join(out)


def scan(paths):
    names = set()
    invocations = 0
    for path in paths:
        raw = path.read_text(encoding="utf-8")
        text = mask_comments(raw)
        for match in HOOK.finditer(text):
            # Macro definitions describe the implementation, not hook sites.
            line_start = text.rfind("\n", 0, match.start()) + 1
            if text[line_start:match.start()].lstrip().startswith("#define"):
                continue
            invocations += 1
            rest = text[match.end():]
            literal = STRING.match(rest.lstrip())
            if not literal:
                line = text.count("\n", 0, match.start()) + 1
                raise ValueError(f"{path}:{line}: TRACE_NONDET_* first argument must be a string literal")
            names.add(bytes(literal.group(1), "utf-8").decode("unicode_escape"))
    return sorted(names), invocations


def render(names, invocations):
    rows = "".join(f'    X("{name}") \\\n' for name in names)
    if rows: rows = rows[:-3] + "\n"
    return ("/* Generated by tools/gen_nondet_builtins.py; do not edit. */\n"
            "#ifndef EIGS_NONDET_BUILTINS_H\n#define EIGS_NONDET_BUILTINS_H\n"
            f"#define EIGS_CAPTURED_BUILTIN_COUNT {len(names)}\n"
            f"#define EIGS_CAPTURED_HOOK_COUNT {invocations}\n"
            "#define EIGS_CAPTURED_BUILTINS(X) \\\n" + rows +
            "#endif\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", required=True)
    ap.add_argument("sources", nargs="+")
    args = ap.parse_args()
    try:
        names, invocations = scan([pathlib.Path(p) for p in args.sources])
    except (OSError, UnicodeError, ValueError) as exc:
        print(f"gen_nondet_builtins: error: {exc}", file=sys.stderr)
        return 1
    content = render(names, invocations)
    out = pathlib.Path(args.output)
    if not out.exists() or out.read_text(encoding="utf-8") != content:
        out.write_text(content, encoding="utf-8")
    else:
        # Mark a successful rescan newer than its source prerequisites. Without
        # this, an unchanged result leaves make invoking the generator forever.
        out.touch()
    print(f"nondet metadata: examined={len(names)} hooks={invocations}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
