#!/bin/bash
# Generate src/lsp_builtin_index.h — the builtin table the LSP serves as
# completion + hover (#742).
#
# The hand-written builtin_docs[][2] this replaces was the repo's cleanest
# natural experiment in the value of a gate: the two gated registries
# (SANDBOX_ALLOW, the docs) sat at zero drift while the ungated LSP table
# fell to 68 of 235 builtins (29%) plus a phantom `exec`. Generation makes
# it correct by construction, the same cure lsp_stdlib_index.h applied to
# the lib/ half (#590).
#
# Names come from the registration seams themselves:
#   - core: every `env_set_local_owned(env, "name", ...)` line in
#     src/builtins.c, src/builtins_host.c, src/hash.c, src/ext_store.c
#     (the always-compiled registration TUs — store rides the single seam
#     since #742). `__`-prefixed self-test hooks are skipped.
#   - extensions: the X-macro rows of every EIGS_*_BUILTINS group in
#     src/ext_names.h — the LSP describes the LANGUAGE surface, not this
#     binary's build flags (the same rule as lint's E003 binding base).
# Hover detail is the signature comment above the builtin's C definition
# (`/* name of args — description */`, the convention the PR checklist
# enforces for new builtins), scraped from the runtime TUs; builtins whose
# definition never wrote one fall back to a docs/BUILTINS.md pointer —
# back-filling those comments is upstream work, not papered over here.
#
# The generated header is a build artifact, NOT committed (the
# lsp_stdlib_index.h / amalgamation precedent, #397): the Makefile `lsp`
# target and `build.sh lsp` regenerate it before compiling eigenlsp.
#
# Usage: tools/gen_lsp_builtin_index.sh [output-header]
#   default output: src/lsp_builtin_index.h
# Exit 0 on success; nonzero (and no output written) on a parse failure.

set -u
cd "$(dirname "$0")/.."

OUT="${1:-src/lsp_builtin_index.h}"

# LC_ALL=C: deterministic sort + byte-wise awk on any box.
LC_ALL=C
export LC_ALL

CORE_SRCS="src/builtins.c src/builtins_host.c src/hash.c src/ext_store.c"
# TUs scanned for `name of ...` signature comments (core + every extension).
DOC_SRCS="src/builtins.c src/builtins_host.c src/builtins_tensor.c \
          src/hash.c src/ext_store.c src/ext_gfx.c src/ext_http.c \
          src/ext_db.c src/ext_net.c src/model_train.c"

TMP_NAMES=$(mktemp)
TMP_OUT=$(mktemp)
trap 'rm -f "$TMP_NAMES" "$TMP_OUT"' EXIT

# ---- 1. core names from the registration seams -------------------------
# Line shape: env_set_local_owned(env, "name", make_builtin(fn));
grep -h 'env_set_local_owned(env, "' $CORE_SRCS \
    | sed -n 's/.*env_set_local_owned(env, "\([A-Za-z0-9_]*\)".*/\1/p' \
    | grep -v '^__' | sed 's/$/\tcore/' >> "$TMP_NAMES"

# ---- 2. extension names from ext_names.h X-macro groups ----------------
awk '
/^#define EIGS_[A-Z_]+_BUILTINS\(X\)/ {
    group = $2
    sub(/^EIGS_/, "", group); sub(/_BUILTINS\(X\)/, "", group)
    group = tolower(group)
    next
}
/^[ \t]*X\([A-Za-z0-9_]+,/ {
    line = $0
    sub(/^[ \t]*X\(/, "", line)
    sub(/,.*/, "", line)
    if (group != "") printf "%s\t%s\n", line, group
}
/^$/ { group = "" }
' src/ext_names.h >> "$TMP_NAMES"

total=$(sort -u -t"$(printf '\t')" -k1,1 "$TMP_NAMES" | wc -l)
if [ "$total" -eq 0 ]; then
    echo "gen_lsp_builtin_index: extracted 0 names — seam scrape broke" >&2
    exit 1
fi

# ---- 3. emit, resolving each name's signature comment ------------------
sort -u -t"$(printf '\t')" -k1,1 "$TMP_NAMES" | awk -v OUT="$TMP_OUT" -v docs="$DOC_SRCS" '
function c_escape(s) {
    gsub(/\\/, "\\\\", s)
    gsub(/"/, "\\\"", s)
    return s
}
BEGIN {
    FS = "\t"
    # Preload every signature-comment line from the runtime TUs:
    # a comment line whose text starts `name of ` (after comment markers).
    n = split(docs, files, /[ \t]+/)
    for (f = 1; f <= n; f++) {
        if (files[f] == "") continue
        while ((getline line < files[f]) > 0) {
            t = line
            sub(/^[ \t]*\/?\*+[ \t]*/, "", t)          # strip /* or * lead
            sub(/[ \t]*\*+\/[ \t]*$/, "", t)           # strip trailing */
            if (t !~ /^[A-Za-z0-9_]+ of / ) continue
            name = t; sub(/ .*/, "", name)
            if (!(name in sig)) sig[name] = t
        }
        close(files[f])
    }
    print "/* Generated by tools/gen_lsp_builtin_index.sh — DO NOT EDIT (#742)."  > OUT
    print " * Names come from the registration seams + ext_names.h; hover text" > OUT
    print " * from the `name of ...` signature comment above each definition." > OUT
    print " * Regenerated by the Makefile lsp target and build.sh lsp. */"     > OUT
    print "static const char *builtin_docs[][2] = {"                            > OUT
    core = 0; ext = 0; documented = 0
}
{
    name = $1; group = $2
    if (name in sig) {
        detail = sig[name]
        documented++
    } else if (group == "core") {
        detail = name " — builtin; see docs/BUILTINS.md"
    } else {
        detail = name " — " group " extension builtin; see docs/BUILTINS.md"
    }
    if (group == "core") core++; else ext++
    printf "    {\"%s\", \"%s\"},\n", c_escape(name), c_escape(detail) > OUT
}
END {
    print "    {0, 0}"  > OUT
    print "};"          > OUT
    printf "gen_lsp_builtin_index: %d core + %d extension builtins, %d with signature comments\n", core, ext, documented > "/dev/stderr"
}
'
mv "$TMP_OUT" "$OUT"
