#!/bin/bash
# Generate src/lsp_stdlib_index.h — the stdlib (lib/*.eigs) index the LSP
# serves as import-aware completion + hover (#590).
#
# Scrapes every lib/*.eigs for PUBLIC `define name(params)` definitions
# (leading-underscore names are private, per docs/STDLIB.md) plus their
# rule-2 signature comment (`# name of args -> return_type`, docs/STDLIB.md
# "Writing Library Functions"). Functions without a signature comment are
# tolerated: the detail falls back to the `define name(params) as:` shape
# (back-filling the ~200 missing comments is tracked separately — do not
# paper over it here).
#
# Parsing conventions follow tools/stdlib_index_check.sh (cheap grep/awk
# over lib/, zero dependencies — no python). The generated header is a
# build artifact, NOT committed (the build/ amalgamation precedent, #397):
# the Makefile `lsp` target and `build.sh lsp` regenerate it before
# compiling eigenlsp.
#
# Usage: tools/gen_lsp_stdlib_index.sh [output-header]
#   default output: src/lsp_stdlib_index.h
# Exit 0 on success.

set -u
cd "$(dirname "$0")/.."

OUT="${1:-src/lsp_stdlib_index.h}"

# LC_ALL=C: deterministic glob order + byte-wise awk on any box.
LC_ALL=C
export LC_ALL

awk -v OUT="$OUT" '
function c_escape(s) {
    gsub(/\\/, "\\\\", s)
    gsub(/"/, "\\\"", s)
    return s
}
# Signature comment attached to this define: the LAST line in the comment
# block directly above that reads `# <name> of ...` (banner lines like
# `# ---- name: desc ----` never match; note lines below the signature do
# not hide it). Returns "" when the module never wrote one (fallback).
function sig_from_block(name,    i, text, found) {
    found = ""
    for (i = 1; i <= ncb; i++) {
        text = cb[i]
        sub(/^#[ \t]*/, "", text)
        if (index(text, name " of ") == 1) found = text
    }
    return found
}
BEGIN {
    print "/* Generated by tools/gen_lsp_stdlib_index.sh from the lib/ .eigs modules" > OUT
    print " * -- DO NOT EDIT. Public define name(params) definitions + their rule-2" > OUT
    print " * signature comments (docs/STDLIB.md \"Writing Library Functions\"), served" > OUT
    print " * by src/eigenlsp.c as import-aware completion + hover (#590). Fallback" > OUT
    print " * detail is the define shape. Regenerated by the Makefile lsp target /" > OUT
    print " * build.sh lsp; not committed. Columns: module, name, params, detail. */" > OUT
    print "#include <stddef.h>" > OUT
    print "static const char *stdlib_docs[][4] = {" > OUT
}
FNR == 1 {
    module = FILENAME
    sub(/.*\//, "", module)
    sub(/\.eigs$/, "", module)
    ncb = 0
    modules++
}
/^[ \t]*#/ {
    cb[++ncb] = $0
    next
}
/^define[ \t]+[A-Za-z_][A-Za-z0-9_]*/ {
    line = $0
    sub(/^define[ \t]+/, "", line)
    match(line, /^[A-Za-z_][A-Za-z0-9_]*/)
    name = substr(line, 1, RLENGTH)
    rest = substr(line, RLENGTH + 1)
    params = ""
    if (substr(rest, 1, 1) == "(") {
        # No nesting or `is`-defaults in lib parameter lists (verified);
        # the first ")" closes the list.
        p = index(rest, ")")
        params = substr(rest, 2, p - 2)
    }
    if (substr(name, 1, 1) != "_") {
        detail = sig_from_block(name)
        if (detail == "")
            detail = "define " name "(" params ") as:"
        printf "    {\"%s\", \"%s\", \"%s\", \"%s\"},\n", \
            c_escape(module), c_escape(name), c_escape(params), c_escape(detail) > OUT
        funcs++
    }
    ncb = 0
    next
}
{
    # Any non-comment, non-define line (including blank) detaches the block.
    ncb = 0
}
END {
    print "    {NULL, NULL, NULL, NULL}" > OUT
    print "};" > OUT
    printf "lsp_stdlib_index: %d public functions across %d lib modules -> %s\n", \
        funcs, modules, OUT > "/dev/stderr"
}
' lib/*.eigs
