/* Generated by tools/gen_nondet_builtins.py; do not edit. */
#ifndef EIGS_NONDET_BUILTINS_H
#define EIGS_NONDET_BUILTINS_H
#define EIGS_CAPTURED_BUILTIN_COUNT 35
#define EIGS_CAPTURED_HOOK_COUNT 118
#define EIGS_CAPTURED_BUILTINS(X) \
    X("args") \
    X("audio_capture_open") \
    X("audio_capture_read") \
    X("audio_stream_queued") \
    X("clock_unix") \
    X("eigen_generate") \
    X("env_get") \
    X("exe_path") \
    X("file_exists") \
    X("getcwd") \
    X("gfx_read") \
    X("http_post") \
    X("http_request_body") \
    X("http_request_headers") \
    X("http_session_id") \
    X("is_dir") \
    X("is_file") \
    X("ls") \
    X("mkdir") \
    X("monotonic_ms") \
    X("monotonic_ns") \
    X("net_accept") \
    X("net_dial") \
    X("net_listen") \
    X("net_port") \
    X("net_recv") \
    X("net_send") \
    X("random") \
    X("random_hex") \
    X("random_int") \
    X("random_normal") \
    X("read_bytes") \
    X("read_bytes_buf") \
    X("read_line") \
    X("read_text")
#endif
